// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FetchUnit(	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
  input         clock,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
                reset,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
  output [63:0] io_decodeStage_data_inst,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:10:14
  output        io_decodeStage_data_valid,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:10:14
  output [63:0] io_decodeStage_data_pc,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:10:14
  output        io_instSram_en,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:10:14
  output [31:0] io_instSram_addr,	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:10:14
  input  [31:0] io_instSram_rdata	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:10:14
);

  reg  [1:0]  state;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:16:47
  reg  [63:0] pc;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:28:21
  wire [31:0] _io_instSram_addr_T = pc[31:0] + 32'h4;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:28:21, :30:26
  always @(posedge clock) begin	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
    if (reset) begin	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      state <= 2'h0;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47
      pc <= 64'h7FFFFFFC;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:28:{21,49}
    end
    else begin	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      if (state == 2'h0)	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47, :18:17
        state <= 2'h1;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47
      else if (state == 2'h1)	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47, :18:17
        state <= 2'h2;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47
      if (|state)	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:16:47, :28:63
        pc <= {32'h0, _io_instSram_addr_T};	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:28:21, :30:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      `FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      automatic logic [31:0] _RANDOM[0:2];	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      `ifdef INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
        `INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
        end	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
        state = _RANDOM[2'h0][1:0];	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47
        pc = {_RANDOM[2'h0][31:2], _RANDOM[2'h1], _RANDOM[2'h2][1:0]};	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47, :28:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
      `FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_decodeStage_data_inst = {32'h0, io_instSram_rdata};	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :28:21, :34:29
  assign io_decodeStage_data_valid = state == 2'h2;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :16:47, :32:38
  assign io_decodeStage_data_pc = pc;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :28:21
  assign io_instSram_en = ~reset;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :36:24
  assign io_instSram_addr = _io_instSram_addr_T;	// \\playground\\src\\pipeline\\fetch\\FetchUnit.scala:9:7, :30:26
endmodule

module DecodeStage(	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
  input         clock,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
                reset,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
  input  [63:0] io_fetchUnit_data_inst,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:20:14
  input         io_fetchUnit_data_valid,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:20:14
  input  [63:0] io_fetchUnit_data_pc,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:20:14
  output [63:0] io_decodeUnit_data_inst,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:20:14
  output        io_decodeUnit_data_valid,	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:20:14
  output [63:0] io_decodeUnit_data_pc	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:20:14
);

  reg [63:0] data_inst;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:21
  reg        data_valid;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:21
  reg [63:0] data_pc;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:21
  always @(posedge clock) begin	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
    if (reset) begin	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      data_inst <= 64'h0;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:{21,34}
      data_valid <= 1'h0;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:{21,34}
      data_pc <= 64'h0;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:{21,34}
    end
    else begin	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      data_inst <= io_fetchUnit_data_inst;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:21
      data_valid <= io_fetchUnit_data_valid;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:21
      data_pc <= io_fetchUnit_data_pc;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:25:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      `FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      automatic logic [31:0] _RANDOM[0:4];	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      `ifdef INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
        `INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
        end	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
        data_inst = {_RANDOM[3'h0], _RANDOM[3'h1]};	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7, :25:21
        data_valid = _RANDOM[3'h2][0];	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7, :25:21
        data_pc = {_RANDOM[3'h2][31:1], _RANDOM[3'h3], _RANDOM[3'h4][0]};	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7, :25:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
      `FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_decodeUnit_data_inst = data_inst;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7, :25:21
  assign io_decodeUnit_data_valid = data_valid;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7, :25:21
  assign io_decodeUnit_data_pc = data_pc;	// \\playground\\src\\pipeline\\decode\\DecodeStage.scala:19:7, :25:21
endmodule

module Decoder(	// \\playground\\src\\pipeline\\decode\\Decoder.scala:8:7
  input  [63:0] io_in_inst,	// \\playground\\src\\pipeline\\decode\\Decoder.scala:9:14
  output [4:0]  io_out_info_src1_raddr,	// \\playground\\src\\pipeline\\decode\\Decoder.scala:9:14
                io_out_info_src2_raddr,	// \\playground\\src\\pipeline\\decode\\Decoder.scala:9:14
  output [5:0]  io_out_info_op,	// \\playground\\src\\pipeline\\decode\\Decoder.scala:9:14
  output        io_out_info_reg_wen,	// \\playground\\src\\pipeline\\decode\\Decoder.scala:9:14
  output [4:0]  io_out_info_reg_waddr	// \\playground\\src\\pipeline\\decode\\Decoder.scala:9:14
);

  wire [9:0]  _GEN = {io_in_inst[14:12], io_in_inst[6:0]};	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_0 = _GEN == 10'h13;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [15:0] _GEN_1 = {io_in_inst[31:26], io_in_inst[14:12], io_in_inst[6:0]};	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_2 = _GEN_1 == 16'h93;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_3 = _GEN == 10'h113;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_4 = _GEN == 10'h193;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_5 = _GEN == 10'h213;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_6 = _GEN_1 == 16'h293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_7 = _GEN == 10'h313;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_8 = _GEN == 10'h393;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_9 = _GEN_1 == 16'h4293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [16:0] _GEN_10 = {io_in_inst[31:25], io_in_inst[14:12], io_in_inst[6:0]};	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_11 = _GEN_10 == 17'h33;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_12 = _GEN_10 == 17'hB3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_13 = _GEN_10 == 17'h133;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_14 = _GEN_10 == 17'h1B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_15 = _GEN_10 == 17'h233;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_16 = _GEN_10 == 17'h2B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_17 = _GEN_10 == 17'h333;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_18 = _GEN_10 == 17'h3B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_19 = _GEN_10 == 17'h8033;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_20 = _GEN_10 == 17'h82B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_21 = _GEN == 10'h1B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_22 = _GEN_10 == 17'h9B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_23 = _GEN_10 == 17'h29B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_24 = _GEN_10 == 17'h829B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_25 = _GEN_10 == 17'hBB;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_26 = _GEN_10 == 17'h2BB;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_27 = _GEN_10 == 17'h82BB;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_28 = _GEN_10 == 17'h3B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_29 = _GEN_10 == 17'h803B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_30 = io_in_inst[6:0] == 7'h17 | io_in_inst[6:0] == 7'h37;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        instrType =
    _GEN_0 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9
    | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18
    | _GEN_19 | _GEN_20 | _GEN_30 | _GEN_21 | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_25
    | _GEN_26 | _GEN_27 | _GEN_28 | _GEN_29;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  assign io_out_info_src1_raddr = io_in_inst[19:15];	// \\playground\\src\\pipeline\\decode\\Decoder.scala:8:7, :24:27
  assign io_out_info_src2_raddr = io_in_inst[24:20];	// \\playground\\src\\pipeline\\decode\\Decoder.scala:8:7, :24:41
  assign io_out_info_op =
    _GEN_0
      ? 6'h20
      : _GEN_2
          ? 6'h1
          : _GEN_3
              ? 6'h2
              : _GEN_4
                  ? 6'h3
                  : _GEN_5
                      ? 6'h4
                      : _GEN_6
                          ? 6'h5
                          : _GEN_7
                              ? 6'h6
                              : _GEN_8
                                  ? 6'h7
                                  : _GEN_9
                                      ? 6'hD
                                      : _GEN_11
                                          ? 6'h20
                                          : _GEN_12
                                              ? 6'h1
                                              : _GEN_13
                                                  ? 6'h2
                                                  : _GEN_14
                                                      ? 6'h3
                                                      : _GEN_15
                                                          ? 6'h4
                                                          : _GEN_16
                                                              ? 6'h5
                                                              : _GEN_17
                                                                  ? 6'h6
                                                                  : _GEN_18
                                                                      ? 6'h7
                                                                      : _GEN_19
                                                                          ? 6'h8
                                                                          : _GEN_20
                                                                              ? 6'hD
                                                                              : _GEN_30
                                                                                  ? 6'h20
                                                                                  : _GEN_21
                                                                                      ? 6'h30
                                                                                      : _GEN_22
                                                                                          ? 6'h11
                                                                                          : _GEN_23
                                                                                              ? 6'h15
                                                                                              : _GEN_24
                                                                                                  ? 6'h1D
                                                                                                  : _GEN_25
                                                                                                      ? 6'h11
                                                                                                      : _GEN_26
                                                                                                          ? 6'h15
                                                                                                          : _GEN_27
                                                                                                              ? 6'h1D
                                                                                                              : _GEN_28
                                                                                                                  ? 6'h30
                                                                                                                  : _GEN_29
                                                                                                                      ? 6'h18
                                                                                                                      : 6'h20;	// \\playground\\src\\pipeline\\decode\\Decoder.scala:8:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  assign io_out_info_reg_wen = instrType;	// \\playground\\src\\pipeline\\decode\\Decoder.scala:8:7, src/main/scala/chisel3/util/Lookup.scala:34:39
  assign io_out_info_reg_waddr = instrType ? io_in_inst[11:7] : 5'h0;	// \\playground\\src\\pipeline\\decode\\Decoder.scala:8:7, :24:55, :31:32, src/main/scala/chisel3/util/Lookup.scala:34:39
endmodule

module DecodeUnit(	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:8:7
  input  [63:0] io_decodeStage_data_inst,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  input         io_decodeStage_data_valid,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  input  [63:0] io_decodeStage_data_pc,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output [4:0]  io_regfile_src1_raddr,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  input  [63:0] io_regfile_src1_rdata,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output [4:0]  io_regfile_src2_raddr,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  input  [63:0] io_regfile_src2_rdata,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output [63:0] io_executeStage_data_pc,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output        io_executeStage_data_info_valid,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output [5:0]  io_executeStage_data_info_op,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output        io_executeStage_data_info_reg_wen,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output [4:0]  io_executeStage_data_info_reg_waddr,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
  output [63:0] io_executeStage_data_src_info_src1_data,	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
                io_executeStage_data_src_info_src2_data	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:9:14
);

  Decoder Decoder (	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:17:23
    .io_in_inst             (io_decodeStage_data_inst),
    .io_out_info_src1_raddr (io_regfile_src1_raddr),
    .io_out_info_src2_raddr (io_regfile_src2_raddr),
    .io_out_info_op         (io_executeStage_data_info_op),
    .io_out_info_reg_wen    (io_executeStage_data_info_reg_wen),
    .io_out_info_reg_waddr  (io_executeStage_data_info_reg_waddr)
  );
  assign io_executeStage_data_pc = io_decodeStage_data_pc;	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:8:7
  assign io_executeStage_data_info_valid = io_decodeStage_data_valid;	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:8:7
  assign io_executeStage_data_src_info_src1_data = io_regfile_src1_rdata;	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:8:7
  assign io_executeStage_data_src_info_src2_data = io_regfile_src2_rdata;	// \\playground\\src\\pipeline\\decode\\DecodeUnit.scala:8:7
endmodule

module ARegFile(	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
  input         clock,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
                reset,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
  input  [4:0]  io_read_src1_raddr,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
  output [63:0] io_read_src1_rdata,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
  input  [4:0]  io_read_src2_raddr,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
  output [63:0] io_read_src2_rdata,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
  input         io_write_wen,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
  input  [4:0]  io_write_waddr,	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
  input  [63:0] io_write_wdata	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:26:14
);

  reg  [63:0]       regs_0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_1;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_2;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_3;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_4;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_5;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_6;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_7;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_8;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_9;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_10;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_11;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_12;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_13;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_14;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_15;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_16;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_17;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_18;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_19;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_20;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_21;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_22;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_23;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_24;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_25;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_26;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_27;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_28;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_29;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_30;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  reg  [63:0]       regs_31;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
  wire [31:0][63:0] _GEN =
    {{regs_31},
     {regs_30},
     {regs_29},
     {regs_28},
     {regs_27},
     {regs_26},
     {regs_25},
     {regs_24},
     {regs_23},
     {regs_22},
     {regs_21},
     {regs_20},
     {regs_19},
     {regs_18},
     {regs_17},
     {regs_16},
     {regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {regs_0}};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :44:24
  always @(posedge clock) begin	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
    if (reset) begin	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      regs_0 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_1 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_2 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_3 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_4 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_5 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_6 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_7 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_8 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_9 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_10 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_11 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_12 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_13 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_14 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_15 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_16 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_17 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_18 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_19 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_20 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_21 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_22 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_23 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_24 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_25 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_26 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_27 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_28 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_29 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_30 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
      regs_31 <= 64'h0;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:{21,29}
    end
    else begin	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      automatic logic _GEN_0 = io_write_wen & (|io_write_waddr);	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:35:{21,39}
      if (_GEN_0 & ~(|io_write_waddr))	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,39,48}, :36:26
        regs_0 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h1)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_1 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h2)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_2 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h3)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_3 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h4)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_4 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h5)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_5 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h6)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_6 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h7)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_7 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h8)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_8 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h9)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_9 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'hA)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_10 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'hB)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_11 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'hC)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_12 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'hD)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_13 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'hE)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_14 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'hF)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_15 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h10)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_16 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h11)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_17 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h12)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_18 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h13)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_19 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h14)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_20 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h15)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_21 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h16)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_22 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h17)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_23 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h18)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_24 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h19)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_25 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h1A)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_26 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h1B)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_27 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h1C)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_28 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h1D)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_29 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & io_write_waddr == 5'h1E)	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_30 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
      if (_GEN_0 & (&io_write_waddr))	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21, :35:{21,48}, :36:26
        regs_31 <= io_write_wdata;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:32:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      `FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      automatic logic [31:0] _RANDOM[0:63];	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      `ifdef INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
        `INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          _RANDOM[i[5:0]] = `RANDOM;	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
        end	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
        regs_0 = {_RANDOM[6'h0], _RANDOM[6'h1]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_1 = {_RANDOM[6'h2], _RANDOM[6'h3]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_2 = {_RANDOM[6'h4], _RANDOM[6'h5]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_3 = {_RANDOM[6'h6], _RANDOM[6'h7]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_4 = {_RANDOM[6'h8], _RANDOM[6'h9]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_5 = {_RANDOM[6'hA], _RANDOM[6'hB]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_6 = {_RANDOM[6'hC], _RANDOM[6'hD]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_7 = {_RANDOM[6'hE], _RANDOM[6'hF]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_8 = {_RANDOM[6'h10], _RANDOM[6'h11]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_9 = {_RANDOM[6'h12], _RANDOM[6'h13]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_10 = {_RANDOM[6'h14], _RANDOM[6'h15]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_11 = {_RANDOM[6'h16], _RANDOM[6'h17]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_12 = {_RANDOM[6'h18], _RANDOM[6'h19]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_13 = {_RANDOM[6'h1A], _RANDOM[6'h1B]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_14 = {_RANDOM[6'h1C], _RANDOM[6'h1D]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_15 = {_RANDOM[6'h1E], _RANDOM[6'h1F]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_16 = {_RANDOM[6'h20], _RANDOM[6'h21]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_17 = {_RANDOM[6'h22], _RANDOM[6'h23]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_18 = {_RANDOM[6'h24], _RANDOM[6'h25]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_19 = {_RANDOM[6'h26], _RANDOM[6'h27]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_20 = {_RANDOM[6'h28], _RANDOM[6'h29]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_21 = {_RANDOM[6'h2A], _RANDOM[6'h2B]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_22 = {_RANDOM[6'h2C], _RANDOM[6'h2D]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_23 = {_RANDOM[6'h2E], _RANDOM[6'h2F]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_24 = {_RANDOM[6'h30], _RANDOM[6'h31]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_25 = {_RANDOM[6'h32], _RANDOM[6'h33]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_26 = {_RANDOM[6'h34], _RANDOM[6'h35]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_27 = {_RANDOM[6'h36], _RANDOM[6'h37]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_28 = {_RANDOM[6'h38], _RANDOM[6'h39]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_29 = {_RANDOM[6'h3A], _RANDOM[6'h3B]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_30 = {_RANDOM[6'h3C], _RANDOM[6'h3D]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
        regs_31 = {_RANDOM[6'h3E], _RANDOM[6'h3F]};	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
      `FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_read_src1_rdata =
    io_read_src1_raddr == 5'h0 ? 64'h0 : _GEN[io_read_src1_raddr];	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:29, :35:39, :41:{27,36}, :42:24, :44:24
  assign io_read_src2_rdata =
    io_read_src2_raddr == 5'h0 ? 64'h0 : _GEN[io_read_src2_raddr];	// \\playground\\src\\pipeline\\decode\\ARegfile.scala:25:7, :32:29, :35:39, :44:24, :47:{27,36}, :48:24, :50:24
endmodule

module ExecuteStage(	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
  input         clock,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
                reset,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
  input  [63:0] io_decodeUnit_data_pc,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  input         io_decodeUnit_data_info_valid,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  input  [5:0]  io_decodeUnit_data_info_op,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  input         io_decodeUnit_data_info_reg_wen,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  input  [4:0]  io_decodeUnit_data_info_reg_waddr,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  input  [63:0] io_decodeUnit_data_src_info_src1_data,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
                io_decodeUnit_data_src_info_src2_data,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  output [63:0] io_executeUnit_data_pc,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  output        io_executeUnit_data_info_valid,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  output [5:0]  io_executeUnit_data_info_op,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  output        io_executeUnit_data_info_reg_wen,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  output [4:0]  io_executeUnit_data_info_reg_waddr,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
  output [63:0] io_executeUnit_data_src_info_src1_data,	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
                io_executeUnit_data_src_info_src2_data	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:20:14
);

  reg [63:0] data_pc;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  reg        data_info_valid;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  reg [5:0]  data_info_op;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  reg        data_info_reg_wen;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  reg [4:0]  data_info_reg_waddr;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  reg [63:0] data_src_info_src1_data;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  reg [63:0] data_src_info_src2_data;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
  always @(posedge clock) begin	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
    if (reset) begin	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      data_pc <= 64'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
      data_info_valid <= 1'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
      data_info_op <= 6'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
      data_info_reg_wen <= 1'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
      data_info_reg_waddr <= 5'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
      data_src_info_src1_data <= 64'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
      data_src_info_src2_data <= 64'h0;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:{21,34}
    end
    else begin	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      data_pc <= io_decodeUnit_data_pc;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
      data_info_valid <= io_decodeUnit_data_info_valid;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
      data_info_op <= io_decodeUnit_data_info_op;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
      data_info_reg_wen <= io_decodeUnit_data_info_reg_wen;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
      data_info_reg_waddr <= io_decodeUnit_data_info_reg_waddr;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
      data_src_info_src1_data <= io_decodeUnit_data_src_info_src1_data;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
      data_src_info_src2_data <= io_decodeUnit_data_src_info_src2_data;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:25:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      `FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      automatic logic [31:0] _RANDOM[0:6];	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      `ifdef INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
        `INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
        end	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
        data_pc = {_RANDOM[3'h0], _RANDOM[3'h1]};	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
        data_info_valid = _RANDOM[3'h2][0];	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
        data_info_op = _RANDOM[3'h2][16:11];	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
        data_info_reg_wen = _RANDOM[3'h2][17];	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
        data_info_reg_waddr = _RANDOM[3'h2][22:18];	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
        data_src_info_src1_data =
          {_RANDOM[3'h2][31:23], _RANDOM[3'h3], _RANDOM[3'h4][22:0]};	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
        data_src_info_src2_data =
          {_RANDOM[3'h4][31:23], _RANDOM[3'h5], _RANDOM[3'h6][22:0]};	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
      `FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_executeUnit_data_pc = data_pc;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
  assign io_executeUnit_data_info_valid = data_info_valid;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
  assign io_executeUnit_data_info_op = data_info_op;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
  assign io_executeUnit_data_info_reg_wen = data_info_reg_wen;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
  assign io_executeUnit_data_info_reg_waddr = data_info_reg_waddr;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
  assign io_executeUnit_data_src_info_src1_data = data_src_info_src1_data;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
  assign io_executeUnit_data_src_info_src2_data = data_src_info_src2_data;	// \\playground\\src\\pipeline\\execute\\ExecuteStage.scala:19:7, :25:21
endmodule

module Alu(	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:8:7
  input  [5:0]  io_info_op,	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:9:14
  input  [63:0] io_src_info_src1_data,	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:9:14
                io_src_info_src2_data,	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:9:14
  output [63:0] io_result	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:9:14
);

  wire [64:0]  _sum_T_3 =
    {1'h0, io_src_info_src1_data} + {1'h0, io_src_info_src2_data ^ {64{~(io_info_op[5])}}}
    + {64'h0, ~(io_info_op[5])};	// \\playground\\src\\defines\\isa\\Instructions.scala:48:34, \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:17:16, :18:{22,31,37,54}
  wire [63:0]  xor_0 = io_src_info_src1_data ^ io_src_info_src2_data;	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:19:21
  wire [63:0]  shsrc1 =
    io_info_op == 6'h1D
      ? {{32{io_src_info_src1_data[31]}}, io_src_info_src1_data[31:0]}
      : io_info_op == 6'h15
          ? {32'h0, io_src_info_src1_data[31:0]}
          : io_src_info_src1_data;	// \\playground\\src\\defines\\Util.scala:9:20, :10:{44,49}, :17:44, \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:23:48, :25:40
  wire [5:0]   shamt =
    io_info_op[4] ? {1'h0, io_src_info_src2_data[4:0]} : io_src_info_src2_data[5:0];	// \\playground\\src\\defines\\isa\\Instructions.scala:47:34, \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:18:22, :29:{18,47,75}
  wire [126:0] _res_T_1 = {63'h0, shsrc1} << shamt;	// \\playground\\src\\defines\\Util.scala:17:44, \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:23:48, :29:18, :32:34
  wire [63:0]  _GEN = {58'h0, shamt};	// \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:29:18, :36:33
  wire [63:0]  res =
    io_info_op[3:0] == 4'hD
      ? $signed($signed(shsrc1) >>> _GEN)
      : io_info_op[3:0] == 4'h7
          ? io_src_info_src1_data & io_src_info_src2_data
          : io_info_op[3:0] == 4'h6
              ? io_src_info_src1_data | io_src_info_src2_data
              : io_info_op[3:0] == 4'h5
                  ? shsrc1 >> _GEN
                  : io_info_op[3:0] == 4'h4
                      ? xor_0
                      : io_info_op[3:0] == 4'h3
                          ? {63'h0, ~(_sum_T_3[64])}
                          : io_info_op[3:0] == 4'h2
                              ? {63'h0, xor_0[63] ^ ~(_sum_T_3[64])}
                              : io_info_op[3:0] == 4'h1 ? _res_T_1[63:0] : _sum_T_3[63:0];	// \\playground\\src\\defines\\Util.scala:17:44, \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:18:54, :19:21, :20:{16,20}, :21:{19,30}, :23:48, :30:{25,37}, :32:{34,43}, :36:33, :37:31, :38:31, :39:41
  assign io_result = io_info_op[4] ? {{32{res[31]}}, res[31:0]} : res;	// \\playground\\src\\defines\\Util.scala:9:20, :10:49, \\playground\\src\\defines\\isa\\Instructions.scala:47:34, \\playground\\src\\pipeline\\execute\\fu\\Alu.scala:8:7, :30:37, :42:{19,60}
endmodule

module Fu(	// \\playground\\src\\pipeline\\execute\\Fu.scala:9:7
  input  [5:0]  io_data_info_op,	// \\playground\\src\\pipeline\\execute\\Fu.scala:10:14
  input  [63:0] io_data_src_info_src1_data,	// \\playground\\src\\pipeline\\execute\\Fu.scala:10:14
                io_data_src_info_src2_data,	// \\playground\\src\\pipeline\\execute\\Fu.scala:10:14
  output [63:0] io_data_rd_info_wdata	// \\playground\\src\\pipeline\\execute\\Fu.scala:10:14
);

  Alu Alu (	// \\playground\\src\\pipeline\\execute\\Fu.scala:21:19
    .io_info_op            (io_data_info_op),
    .io_src_info_src1_data (io_data_src_info_src1_data),
    .io_src_info_src2_data (io_data_src_info_src2_data),
    .io_result             (io_data_rd_info_wdata)
  );
endmodule

module ExecuteUnit(	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:10:7
  input  [63:0] io_executeStage_data_pc,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  input         io_executeStage_data_info_valid,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  input  [5:0]  io_executeStage_data_info_op,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  input         io_executeStage_data_info_reg_wen,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  input  [4:0]  io_executeStage_data_info_reg_waddr,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  input  [63:0] io_executeStage_data_src_info_src1_data,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
                io_executeStage_data_src_info_src2_data,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  output [63:0] io_memoryStage_data_pc,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  output        io_memoryStage_data_info_valid,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
                io_memoryStage_data_info_reg_wen,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  output [4:0]  io_memoryStage_data_info_reg_waddr,	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
  output [63:0] io_memoryStage_data_rd_info_wdata	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:11:14
);

  Fu Fu (	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:17:18
    .io_data_info_op            (io_executeStage_data_info_op),
    .io_data_src_info_src1_data (io_executeStage_data_src_info_src1_data),
    .io_data_src_info_src2_data (io_executeStage_data_src_info_src2_data),
    .io_data_rd_info_wdata      (io_memoryStage_data_rd_info_wdata)
  );
  assign io_memoryStage_data_pc = io_executeStage_data_pc;	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:10:7
  assign io_memoryStage_data_info_valid = io_executeStage_data_info_valid;	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:10:7
  assign io_memoryStage_data_info_reg_wen = io_executeStage_data_info_reg_wen;	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:10:7
  assign io_memoryStage_data_info_reg_waddr = io_executeStage_data_info_reg_waddr;	// \\playground\\src\\pipeline\\execute\\ExecuteUnit.scala:10:7
endmodule

module MemoryStage(	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
  input         clock,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
                reset,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
  input  [63:0] io_executeUnit_data_pc,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  input         io_executeUnit_data_info_valid,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
                io_executeUnit_data_info_reg_wen,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  input  [4:0]  io_executeUnit_data_info_reg_waddr,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  input  [63:0] io_executeUnit_data_rd_info_wdata,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  output [63:0] io_memoryUnit_data_pc,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  output        io_memoryUnit_data_info_valid,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
                io_memoryUnit_data_info_reg_wen,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  output [4:0]  io_memoryUnit_data_info_reg_waddr,	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
  output [63:0] io_memoryUnit_data_rd_info_wdata	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:21:14
);

  reg [63:0] data_pc;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
  reg        data_info_valid;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
  reg        data_info_reg_wen;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
  reg [4:0]  data_info_reg_waddr;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
  reg [63:0] data_rd_info_wdata;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
  always @(posedge clock) begin	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
    if (reset) begin	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      data_pc <= 64'h0;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:{21,34}
      data_info_valid <= 1'h0;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:{21,34}
      data_info_reg_wen <= 1'h0;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:{21,34}
      data_info_reg_waddr <= 5'h0;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:{21,34}
      data_rd_info_wdata <= 64'h0;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:{21,34}
    end
    else begin	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      data_pc <= io_executeUnit_data_pc;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
      data_info_valid <= io_executeUnit_data_info_valid;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
      data_info_reg_wen <= io_executeUnit_data_info_reg_wen;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
      data_info_reg_waddr <= io_executeUnit_data_info_reg_waddr;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
      data_rd_info_wdata <= io_executeUnit_data_rd_info_wdata;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:26:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      `FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      automatic logic [31:0] _RANDOM[0:4];	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      `ifdef INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
        `INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
        end	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
        data_pc = {_RANDOM[3'h0], _RANDOM[3'h1]};	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
        data_info_valid = _RANDOM[3'h2][0];	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
        data_info_reg_wen = _RANDOM[3'h2][17];	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
        data_info_reg_waddr = _RANDOM[3'h2][22:18];	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
        data_rd_info_wdata = {_RANDOM[3'h2][31:23], _RANDOM[3'h3], _RANDOM[3'h4][22:0]};	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
      `FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_memoryUnit_data_pc = data_pc;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
  assign io_memoryUnit_data_info_valid = data_info_valid;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
  assign io_memoryUnit_data_info_reg_wen = data_info_reg_wen;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
  assign io_memoryUnit_data_info_reg_waddr = data_info_reg_waddr;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
  assign io_memoryUnit_data_rd_info_wdata = data_rd_info_wdata;	// \\playground\\src\\pipeline\\memory\\MemoryStage.scala:20:7, :26:21
endmodule

module MemoryUnit(	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:10:7
  input  [63:0] io_memoryStage_data_pc,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  input         io_memoryStage_data_info_valid,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
                io_memoryStage_data_info_reg_wen,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  input  [4:0]  io_memoryStage_data_info_reg_waddr,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  input  [63:0] io_memoryStage_data_rd_info_wdata,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  output [63:0] io_writeBackStage_data_pc,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  output        io_writeBackStage_data_info_valid,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
                io_writeBackStage_data_info_reg_wen,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  output [4:0]  io_writeBackStage_data_info_reg_waddr,	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
  output [63:0] io_writeBackStage_data_rd_info_wdata	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:11:14
);

  assign io_writeBackStage_data_pc = io_memoryStage_data_pc;	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:10:7
  assign io_writeBackStage_data_info_valid = io_memoryStage_data_info_valid;	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:10:7
  assign io_writeBackStage_data_info_reg_wen = io_memoryStage_data_info_reg_wen;	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:10:7
  assign io_writeBackStage_data_info_reg_waddr = io_memoryStage_data_info_reg_waddr;	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:10:7
  assign io_writeBackStage_data_rd_info_wdata = io_memoryStage_data_rd_info_wdata;	// \\playground\\src\\pipeline\\memory\\MemoryUnit.scala:10:7
endmodule

module WriteBackStage(	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
  input         clock,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
                reset,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
  input  [63:0] io_memoryUnit_data_pc,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  input         io_memoryUnit_data_info_valid,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
                io_memoryUnit_data_info_reg_wen,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  input  [4:0]  io_memoryUnit_data_info_reg_waddr,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  input  [63:0] io_memoryUnit_data_rd_info_wdata,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  output [63:0] io_writeBackUnit_data_pc,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  output        io_writeBackUnit_data_info_valid,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
                io_writeBackUnit_data_info_reg_wen,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  output [4:0]  io_writeBackUnit_data_info_reg_waddr,	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
  output [63:0] io_writeBackUnit_data_rd_info_wdata	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:19:14
);

  reg [63:0] data_pc;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
  reg        data_info_valid;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
  reg        data_info_reg_wen;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
  reg [4:0]  data_info_reg_waddr;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
  reg [63:0] data_rd_info_wdata;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
  always @(posedge clock) begin	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
    if (reset) begin	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      data_pc <= 64'h0;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:{21,34}
      data_info_valid <= 1'h0;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:{21,34}
      data_info_reg_wen <= 1'h0;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:{21,34}
      data_info_reg_waddr <= 5'h0;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:{21,34}
      data_rd_info_wdata <= 64'h0;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:{21,34}
    end
    else begin	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      data_pc <= io_memoryUnit_data_pc;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
      data_info_valid <= io_memoryUnit_data_info_valid;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
      data_info_reg_wen <= io_memoryUnit_data_info_reg_wen;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
      data_info_reg_waddr <= io_memoryUnit_data_info_reg_waddr;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
      data_rd_info_wdata <= io_memoryUnit_data_rd_info_wdata;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:24:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      automatic logic [31:0] _RANDOM[0:4];	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
        `INIT_RANDOM_PROLOG_	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
        end	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
        data_pc = {_RANDOM[3'h0], _RANDOM[3'h1]};	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
        data_info_valid = _RANDOM[3'h2][0];	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
        data_info_reg_wen = _RANDOM[3'h2][17];	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
        data_info_reg_waddr = _RANDOM[3'h2][22:18];	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
        data_rd_info_wdata = {_RANDOM[3'h2][31:23], _RANDOM[3'h3], _RANDOM[3'h4][22:0]};	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
      `FIRRTL_AFTER_INITIAL	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_writeBackUnit_data_pc = data_pc;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
  assign io_writeBackUnit_data_info_valid = data_info_valid;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
  assign io_writeBackUnit_data_info_reg_wen = data_info_reg_wen;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
  assign io_writeBackUnit_data_info_reg_waddr = data_info_reg_waddr;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
  assign io_writeBackUnit_data_rd_info_wdata = data_rd_info_wdata;	// \\playground\\src\\pipeline\\writeback\\WriteBackStage.scala:18:7, :24:21
endmodule

module WriteBackUnit(	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
  input  [63:0] io_writeBackStage_data_pc,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  input         io_writeBackStage_data_info_valid,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
                io_writeBackStage_data_info_reg_wen,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  input  [4:0]  io_writeBackStage_data_info_reg_waddr,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  input  [63:0] io_writeBackStage_data_rd_info_wdata,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  output        io_regfile_wen,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  output [4:0]  io_regfile_waddr,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  output [63:0] io_regfile_wdata,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
                io_debug_pc,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  output        io_debug_commit,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  output [4:0]  io_debug_rf_wnum,	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
  output [63:0] io_debug_rf_wdata	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:10:14
);

  assign io_regfile_wen =
    io_writeBackStage_data_info_valid & io_writeBackStage_data_info_reg_wen;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7, :17:39
  assign io_regfile_waddr = io_writeBackStage_data_info_reg_waddr;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
  assign io_regfile_wdata = io_writeBackStage_data_rd_info_wdata;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
  assign io_debug_pc = io_writeBackStage_data_pc;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
  assign io_debug_commit = io_writeBackStage_data_info_valid;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
  assign io_debug_rf_wnum = io_writeBackStage_data_info_reg_waddr;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
  assign io_debug_rf_wdata = io_writeBackStage_data_rd_info_wdata;	// \\playground\\src\\pipeline\\writeback\\WriteBackUnit.scala:9:7
endmodule

module Core(	// \\playground\\src\\Core.scala:10:7
  input         clock,	// \\playground\\src\\Core.scala:10:7
                reset,	// \\playground\\src\\Core.scala:10:7
  output        io_instSram_en,	// \\playground\\src\\Core.scala:11:14
  output [31:0] io_instSram_addr,	// \\playground\\src\\Core.scala:11:14
  input  [31:0] io_instSram_rdata,	// \\playground\\src\\Core.scala:11:14
  output [63:0] io_debug_pc,	// \\playground\\src\\Core.scala:11:14
  output        io_debug_commit,	// \\playground\\src\\Core.scala:11:14
  output [4:0]  io_debug_rf_wnum,	// \\playground\\src\\Core.scala:11:14
  output [63:0] io_debug_rf_wdata	// \\playground\\src\\Core.scala:11:14
);

  wire        _WriteBackUnit_io_regfile_wen;	// \\playground\\src\\Core.scala:27:30
  wire [4:0]  _WriteBackUnit_io_regfile_waddr;	// \\playground\\src\\Core.scala:27:30
  wire [63:0] _WriteBackUnit_io_regfile_wdata;	// \\playground\\src\\Core.scala:27:30
  wire [63:0] _WriteBackStage_io_writeBackUnit_data_pc;	// \\playground\\src\\Core.scala:26:30
  wire        _WriteBackStage_io_writeBackUnit_data_info_valid;	// \\playground\\src\\Core.scala:26:30
  wire        _WriteBackStage_io_writeBackUnit_data_info_reg_wen;	// \\playground\\src\\Core.scala:26:30
  wire [4:0]  _WriteBackStage_io_writeBackUnit_data_info_reg_waddr;	// \\playground\\src\\Core.scala:26:30
  wire [63:0] _WriteBackStage_io_writeBackUnit_data_rd_info_wdata;	// \\playground\\src\\Core.scala:26:30
  wire [63:0] _MemoryUnit_io_writeBackStage_data_pc;	// \\playground\\src\\Core.scala:25:30
  wire        _MemoryUnit_io_writeBackStage_data_info_valid;	// \\playground\\src\\Core.scala:25:30
  wire        _MemoryUnit_io_writeBackStage_data_info_reg_wen;	// \\playground\\src\\Core.scala:25:30
  wire [4:0]  _MemoryUnit_io_writeBackStage_data_info_reg_waddr;	// \\playground\\src\\Core.scala:25:30
  wire [63:0] _MemoryUnit_io_writeBackStage_data_rd_info_wdata;	// \\playground\\src\\Core.scala:25:30
  wire [63:0] _MemoryStage_io_memoryUnit_data_pc;	// \\playground\\src\\Core.scala:24:30
  wire        _MemoryStage_io_memoryUnit_data_info_valid;	// \\playground\\src\\Core.scala:24:30
  wire        _MemoryStage_io_memoryUnit_data_info_reg_wen;	// \\playground\\src\\Core.scala:24:30
  wire [4:0]  _MemoryStage_io_memoryUnit_data_info_reg_waddr;	// \\playground\\src\\Core.scala:24:30
  wire [63:0] _MemoryStage_io_memoryUnit_data_rd_info_wdata;	// \\playground\\src\\Core.scala:24:30
  wire [63:0] _ExecuteUnit_io_memoryStage_data_pc;	// \\playground\\src\\Core.scala:23:30
  wire        _ExecuteUnit_io_memoryStage_data_info_valid;	// \\playground\\src\\Core.scala:23:30
  wire        _ExecuteUnit_io_memoryStage_data_info_reg_wen;	// \\playground\\src\\Core.scala:23:30
  wire [4:0]  _ExecuteUnit_io_memoryStage_data_info_reg_waddr;	// \\playground\\src\\Core.scala:23:30
  wire [63:0] _ExecuteUnit_io_memoryStage_data_rd_info_wdata;	// \\playground\\src\\Core.scala:23:30
  wire [63:0] _ExecuteStage_io_executeUnit_data_pc;	// \\playground\\src\\Core.scala:22:30
  wire        _ExecuteStage_io_executeUnit_data_info_valid;	// \\playground\\src\\Core.scala:22:30
  wire [5:0]  _ExecuteStage_io_executeUnit_data_info_op;	// \\playground\\src\\Core.scala:22:30
  wire        _ExecuteStage_io_executeUnit_data_info_reg_wen;	// \\playground\\src\\Core.scala:22:30
  wire [4:0]  _ExecuteStage_io_executeUnit_data_info_reg_waddr;	// \\playground\\src\\Core.scala:22:30
  wire [63:0] _ExecuteStage_io_executeUnit_data_src_info_src1_data;	// \\playground\\src\\Core.scala:22:30
  wire [63:0] _ExecuteStage_io_executeUnit_data_src_info_src2_data;	// \\playground\\src\\Core.scala:22:30
  wire [63:0] _ARegFile_io_read_src1_rdata;	// \\playground\\src\\Core.scala:21:30
  wire [63:0] _ARegFile_io_read_src2_rdata;	// \\playground\\src\\Core.scala:21:30
  wire [4:0]  _DecodeUnit_io_regfile_src1_raddr;	// \\playground\\src\\Core.scala:20:30
  wire [4:0]  _DecodeUnit_io_regfile_src2_raddr;	// \\playground\\src\\Core.scala:20:30
  wire [63:0] _DecodeUnit_io_executeStage_data_pc;	// \\playground\\src\\Core.scala:20:30
  wire        _DecodeUnit_io_executeStage_data_info_valid;	// \\playground\\src\\Core.scala:20:30
  wire [5:0]  _DecodeUnit_io_executeStage_data_info_op;	// \\playground\\src\\Core.scala:20:30
  wire        _DecodeUnit_io_executeStage_data_info_reg_wen;	// \\playground\\src\\Core.scala:20:30
  wire [4:0]  _DecodeUnit_io_executeStage_data_info_reg_waddr;	// \\playground\\src\\Core.scala:20:30
  wire [63:0] _DecodeUnit_io_executeStage_data_src_info_src1_data;	// \\playground\\src\\Core.scala:20:30
  wire [63:0] _DecodeUnit_io_executeStage_data_src_info_src2_data;	// \\playground\\src\\Core.scala:20:30
  wire [63:0] _DecodeStage_io_decodeUnit_data_inst;	// \\playground\\src\\Core.scala:19:30
  wire        _DecodeStage_io_decodeUnit_data_valid;	// \\playground\\src\\Core.scala:19:30
  wire [63:0] _DecodeStage_io_decodeUnit_data_pc;	// \\playground\\src\\Core.scala:19:30
  wire [63:0] _FetchUnit_io_decodeStage_data_inst;	// \\playground\\src\\Core.scala:18:30
  wire        _FetchUnit_io_decodeStage_data_valid;	// \\playground\\src\\Core.scala:18:30
  wire [63:0] _FetchUnit_io_decodeStage_data_pc;	// \\playground\\src\\Core.scala:18:30
  FetchUnit FetchUnit (	// \\playground\\src\\Core.scala:18:30
    .clock                     (clock),
    .reset                     (reset),
    .io_decodeStage_data_inst  (_FetchUnit_io_decodeStage_data_inst),
    .io_decodeStage_data_valid (_FetchUnit_io_decodeStage_data_valid),
    .io_decodeStage_data_pc    (_FetchUnit_io_decodeStage_data_pc),
    .io_instSram_en            (io_instSram_en),
    .io_instSram_addr          (io_instSram_addr),
    .io_instSram_rdata         (io_instSram_rdata)
  );
  DecodeStage DecodeStage (	// \\playground\\src\\Core.scala:19:30
    .clock                    (clock),
    .reset                    (reset),
    .io_fetchUnit_data_inst   (_FetchUnit_io_decodeStage_data_inst),	// \\playground\\src\\Core.scala:18:30
    .io_fetchUnit_data_valid  (_FetchUnit_io_decodeStage_data_valid),	// \\playground\\src\\Core.scala:18:30
    .io_fetchUnit_data_pc     (_FetchUnit_io_decodeStage_data_pc),	// \\playground\\src\\Core.scala:18:30
    .io_decodeUnit_data_inst  (_DecodeStage_io_decodeUnit_data_inst),
    .io_decodeUnit_data_valid (_DecodeStage_io_decodeUnit_data_valid),
    .io_decodeUnit_data_pc    (_DecodeStage_io_decodeUnit_data_pc)
  );
  DecodeUnit DecodeUnit (	// \\playground\\src\\Core.scala:20:30
    .io_decodeStage_data_inst                (_DecodeStage_io_decodeUnit_data_inst),	// \\playground\\src\\Core.scala:19:30
    .io_decodeStage_data_valid               (_DecodeStage_io_decodeUnit_data_valid),	// \\playground\\src\\Core.scala:19:30
    .io_decodeStage_data_pc                  (_DecodeStage_io_decodeUnit_data_pc),	// \\playground\\src\\Core.scala:19:30
    .io_regfile_src1_raddr                   (_DecodeUnit_io_regfile_src1_raddr),
    .io_regfile_src1_rdata                   (_ARegFile_io_read_src1_rdata),	// \\playground\\src\\Core.scala:21:30
    .io_regfile_src2_raddr                   (_DecodeUnit_io_regfile_src2_raddr),
    .io_regfile_src2_rdata                   (_ARegFile_io_read_src2_rdata),	// \\playground\\src\\Core.scala:21:30
    .io_executeStage_data_pc                 (_DecodeUnit_io_executeStage_data_pc),
    .io_executeStage_data_info_valid
      (_DecodeUnit_io_executeStage_data_info_valid),
    .io_executeStage_data_info_op            (_DecodeUnit_io_executeStage_data_info_op),
    .io_executeStage_data_info_reg_wen
      (_DecodeUnit_io_executeStage_data_info_reg_wen),
    .io_executeStage_data_info_reg_waddr
      (_DecodeUnit_io_executeStage_data_info_reg_waddr),
    .io_executeStage_data_src_info_src1_data
      (_DecodeUnit_io_executeStage_data_src_info_src1_data),
    .io_executeStage_data_src_info_src2_data
      (_DecodeUnit_io_executeStage_data_src_info_src2_data)
  );
  ARegFile ARegFile (	// \\playground\\src\\Core.scala:21:30
    .clock              (clock),
    .reset              (reset),
    .io_read_src1_raddr (_DecodeUnit_io_regfile_src1_raddr),	// \\playground\\src\\Core.scala:20:30
    .io_read_src1_rdata (_ARegFile_io_read_src1_rdata),
    .io_read_src2_raddr (_DecodeUnit_io_regfile_src2_raddr),	// \\playground\\src\\Core.scala:20:30
    .io_read_src2_rdata (_ARegFile_io_read_src2_rdata),
    .io_write_wen       (_WriteBackUnit_io_regfile_wen),	// \\playground\\src\\Core.scala:27:30
    .io_write_waddr     (_WriteBackUnit_io_regfile_waddr),	// \\playground\\src\\Core.scala:27:30
    .io_write_wdata     (_WriteBackUnit_io_regfile_wdata)	// \\playground\\src\\Core.scala:27:30
  );
  ExecuteStage ExecuteStage (	// \\playground\\src\\Core.scala:22:30
    .clock                                  (clock),
    .reset                                  (reset),
    .io_decodeUnit_data_pc                  (_DecodeUnit_io_executeStage_data_pc),	// \\playground\\src\\Core.scala:20:30
    .io_decodeUnit_data_info_valid          (_DecodeUnit_io_executeStage_data_info_valid),	// \\playground\\src\\Core.scala:20:30
    .io_decodeUnit_data_info_op             (_DecodeUnit_io_executeStage_data_info_op),	// \\playground\\src\\Core.scala:20:30
    .io_decodeUnit_data_info_reg_wen
      (_DecodeUnit_io_executeStage_data_info_reg_wen),	// \\playground\\src\\Core.scala:20:30
    .io_decodeUnit_data_info_reg_waddr
      (_DecodeUnit_io_executeStage_data_info_reg_waddr),	// \\playground\\src\\Core.scala:20:30
    .io_decodeUnit_data_src_info_src1_data
      (_DecodeUnit_io_executeStage_data_src_info_src1_data),	// \\playground\\src\\Core.scala:20:30
    .io_decodeUnit_data_src_info_src2_data
      (_DecodeUnit_io_executeStage_data_src_info_src2_data),	// \\playground\\src\\Core.scala:20:30
    .io_executeUnit_data_pc                 (_ExecuteStage_io_executeUnit_data_pc),
    .io_executeUnit_data_info_valid
      (_ExecuteStage_io_executeUnit_data_info_valid),
    .io_executeUnit_data_info_op            (_ExecuteStage_io_executeUnit_data_info_op),
    .io_executeUnit_data_info_reg_wen
      (_ExecuteStage_io_executeUnit_data_info_reg_wen),
    .io_executeUnit_data_info_reg_waddr
      (_ExecuteStage_io_executeUnit_data_info_reg_waddr),
    .io_executeUnit_data_src_info_src1_data
      (_ExecuteStage_io_executeUnit_data_src_info_src1_data),
    .io_executeUnit_data_src_info_src2_data
      (_ExecuteStage_io_executeUnit_data_src_info_src2_data)
  );
  ExecuteUnit ExecuteUnit (	// \\playground\\src\\Core.scala:23:30
    .io_executeStage_data_pc                 (_ExecuteStage_io_executeUnit_data_pc),	// \\playground\\src\\Core.scala:22:30
    .io_executeStage_data_info_valid
      (_ExecuteStage_io_executeUnit_data_info_valid),	// \\playground\\src\\Core.scala:22:30
    .io_executeStage_data_info_op            (_ExecuteStage_io_executeUnit_data_info_op),	// \\playground\\src\\Core.scala:22:30
    .io_executeStage_data_info_reg_wen
      (_ExecuteStage_io_executeUnit_data_info_reg_wen),	// \\playground\\src\\Core.scala:22:30
    .io_executeStage_data_info_reg_waddr
      (_ExecuteStage_io_executeUnit_data_info_reg_waddr),	// \\playground\\src\\Core.scala:22:30
    .io_executeStage_data_src_info_src1_data
      (_ExecuteStage_io_executeUnit_data_src_info_src1_data),	// \\playground\\src\\Core.scala:22:30
    .io_executeStage_data_src_info_src2_data
      (_ExecuteStage_io_executeUnit_data_src_info_src2_data),	// \\playground\\src\\Core.scala:22:30
    .io_memoryStage_data_pc                  (_ExecuteUnit_io_memoryStage_data_pc),
    .io_memoryStage_data_info_valid
      (_ExecuteUnit_io_memoryStage_data_info_valid),
    .io_memoryStage_data_info_reg_wen
      (_ExecuteUnit_io_memoryStage_data_info_reg_wen),
    .io_memoryStage_data_info_reg_waddr
      (_ExecuteUnit_io_memoryStage_data_info_reg_waddr),
    .io_memoryStage_data_rd_info_wdata
      (_ExecuteUnit_io_memoryStage_data_rd_info_wdata)
  );
  MemoryStage MemoryStage (	// \\playground\\src\\Core.scala:24:30
    .clock                              (clock),
    .reset                              (reset),
    .io_executeUnit_data_pc             (_ExecuteUnit_io_memoryStage_data_pc),	// \\playground\\src\\Core.scala:23:30
    .io_executeUnit_data_info_valid     (_ExecuteUnit_io_memoryStage_data_info_valid),	// \\playground\\src\\Core.scala:23:30
    .io_executeUnit_data_info_reg_wen   (_ExecuteUnit_io_memoryStage_data_info_reg_wen),	// \\playground\\src\\Core.scala:23:30
    .io_executeUnit_data_info_reg_waddr (_ExecuteUnit_io_memoryStage_data_info_reg_waddr),	// \\playground\\src\\Core.scala:23:30
    .io_executeUnit_data_rd_info_wdata  (_ExecuteUnit_io_memoryStage_data_rd_info_wdata),	// \\playground\\src\\Core.scala:23:30
    .io_memoryUnit_data_pc              (_MemoryStage_io_memoryUnit_data_pc),
    .io_memoryUnit_data_info_valid      (_MemoryStage_io_memoryUnit_data_info_valid),
    .io_memoryUnit_data_info_reg_wen    (_MemoryStage_io_memoryUnit_data_info_reg_wen),
    .io_memoryUnit_data_info_reg_waddr  (_MemoryStage_io_memoryUnit_data_info_reg_waddr),
    .io_memoryUnit_data_rd_info_wdata   (_MemoryStage_io_memoryUnit_data_rd_info_wdata)
  );
  MemoryUnit MemoryUnit (	// \\playground\\src\\Core.scala:25:30
    .io_memoryStage_data_pc                (_MemoryStage_io_memoryUnit_data_pc),	// \\playground\\src\\Core.scala:24:30
    .io_memoryStage_data_info_valid        (_MemoryStage_io_memoryUnit_data_info_valid),	// \\playground\\src\\Core.scala:24:30
    .io_memoryStage_data_info_reg_wen      (_MemoryStage_io_memoryUnit_data_info_reg_wen),	// \\playground\\src\\Core.scala:24:30
    .io_memoryStage_data_info_reg_waddr
      (_MemoryStage_io_memoryUnit_data_info_reg_waddr),	// \\playground\\src\\Core.scala:24:30
    .io_memoryStage_data_rd_info_wdata
      (_MemoryStage_io_memoryUnit_data_rd_info_wdata),	// \\playground\\src\\Core.scala:24:30
    .io_writeBackStage_data_pc             (_MemoryUnit_io_writeBackStage_data_pc),
    .io_writeBackStage_data_info_valid
      (_MemoryUnit_io_writeBackStage_data_info_valid),
    .io_writeBackStage_data_info_reg_wen
      (_MemoryUnit_io_writeBackStage_data_info_reg_wen),
    .io_writeBackStage_data_info_reg_waddr
      (_MemoryUnit_io_writeBackStage_data_info_reg_waddr),
    .io_writeBackStage_data_rd_info_wdata
      (_MemoryUnit_io_writeBackStage_data_rd_info_wdata)
  );
  WriteBackStage WriteBackStage (	// \\playground\\src\\Core.scala:26:30
    .clock                                (clock),
    .reset                                (reset),
    .io_memoryUnit_data_pc                (_MemoryUnit_io_writeBackStage_data_pc),	// \\playground\\src\\Core.scala:25:30
    .io_memoryUnit_data_info_valid        (_MemoryUnit_io_writeBackStage_data_info_valid),	// \\playground\\src\\Core.scala:25:30
    .io_memoryUnit_data_info_reg_wen
      (_MemoryUnit_io_writeBackStage_data_info_reg_wen),	// \\playground\\src\\Core.scala:25:30
    .io_memoryUnit_data_info_reg_waddr
      (_MemoryUnit_io_writeBackStage_data_info_reg_waddr),	// \\playground\\src\\Core.scala:25:30
    .io_memoryUnit_data_rd_info_wdata
      (_MemoryUnit_io_writeBackStage_data_rd_info_wdata),	// \\playground\\src\\Core.scala:25:30
    .io_writeBackUnit_data_pc             (_WriteBackStage_io_writeBackUnit_data_pc),
    .io_writeBackUnit_data_info_valid
      (_WriteBackStage_io_writeBackUnit_data_info_valid),
    .io_writeBackUnit_data_info_reg_wen
      (_WriteBackStage_io_writeBackUnit_data_info_reg_wen),
    .io_writeBackUnit_data_info_reg_waddr
      (_WriteBackStage_io_writeBackUnit_data_info_reg_waddr),
    .io_writeBackUnit_data_rd_info_wdata
      (_WriteBackStage_io_writeBackUnit_data_rd_info_wdata)
  );
  WriteBackUnit WriteBackUnit (	// \\playground\\src\\Core.scala:27:30
    .io_writeBackStage_data_pc             (_WriteBackStage_io_writeBackUnit_data_pc),	// \\playground\\src\\Core.scala:26:30
    .io_writeBackStage_data_info_valid
      (_WriteBackStage_io_writeBackUnit_data_info_valid),	// \\playground\\src\\Core.scala:26:30
    .io_writeBackStage_data_info_reg_wen
      (_WriteBackStage_io_writeBackUnit_data_info_reg_wen),	// \\playground\\src\\Core.scala:26:30
    .io_writeBackStage_data_info_reg_waddr
      (_WriteBackStage_io_writeBackUnit_data_info_reg_waddr),	// \\playground\\src\\Core.scala:26:30
    .io_writeBackStage_data_rd_info_wdata
      (_WriteBackStage_io_writeBackUnit_data_rd_info_wdata),	// \\playground\\src\\Core.scala:26:30
    .io_regfile_wen                        (_WriteBackUnit_io_regfile_wen),
    .io_regfile_waddr                      (_WriteBackUnit_io_regfile_waddr),
    .io_regfile_wdata                      (_WriteBackUnit_io_regfile_wdata),
    .io_debug_pc                           (io_debug_pc),
    .io_debug_commit                       (io_debug_commit),
    .io_debug_rf_wnum                      (io_debug_rf_wnum),
    .io_debug_rf_wdata                     (io_debug_rf_wdata)
  );
endmodule

module PuaCpu(	// \\playground\\src\\PuaCpu.scala:6:7
  input         clock,	// \\playground\\src\\PuaCpu.scala:6:7
                reset,	// \\playground\\src\\PuaCpu.scala:6:7
                io_ext_int_mei,	// \\playground\\src\\PuaCpu.scala:7:14
                io_ext_int_mti,	// \\playground\\src\\PuaCpu.scala:7:14
                io_ext_int_msi,	// \\playground\\src\\PuaCpu.scala:7:14
  output        io_inst_sram_en,	// \\playground\\src\\PuaCpu.scala:7:14
  output [31:0] io_inst_sram_addr,	// \\playground\\src\\PuaCpu.scala:7:14
                io_inst_sram_wdata,	// \\playground\\src\\PuaCpu.scala:7:14
  output [3:0]  io_inst_sram_wen,	// \\playground\\src\\PuaCpu.scala:7:14
  input  [31:0] io_inst_sram_rdata,	// \\playground\\src\\PuaCpu.scala:7:14
  output        io_data_sram_en,	// \\playground\\src\\PuaCpu.scala:7:14
  output [31:0] io_data_sram_addr,	// \\playground\\src\\PuaCpu.scala:7:14
  output [63:0] io_data_sram_wdata,	// \\playground\\src\\PuaCpu.scala:7:14
  output [7:0]  io_data_sram_wen,	// \\playground\\src\\PuaCpu.scala:7:14
  input  [63:0] io_data_sram_rdata,	// \\playground\\src\\PuaCpu.scala:7:14
  output [63:0] io_debug_pc,	// \\playground\\src\\PuaCpu.scala:7:14
  output        io_debug_commit,	// \\playground\\src\\PuaCpu.scala:7:14
  output [4:0]  io_debug_rf_wnum,	// \\playground\\src\\PuaCpu.scala:7:14
  output [63:0] io_debug_rf_wdata	// \\playground\\src\\PuaCpu.scala:7:14
);

  Core core (	// \\playground\\src\\PuaCpu.scala:14:20
    .clock             (clock),
    .reset             (reset),
    .io_instSram_en    (io_inst_sram_en),
    .io_instSram_addr  (io_inst_sram_addr),
    .io_instSram_rdata (io_inst_sram_rdata),
    .io_debug_pc       (io_debug_pc),
    .io_debug_commit   (io_debug_commit),
    .io_debug_rf_wnum  (io_debug_rf_wnum),
    .io_debug_rf_wdata (io_debug_rf_wdata)
  );
  assign io_inst_sram_wdata = 32'h0;	// \\playground\\src\\PuaCpu.scala:6:7, :14:20
  assign io_inst_sram_wen = 4'h0;	// \\playground\\src\\PuaCpu.scala:6:7, :14:20
  assign io_data_sram_en = 1'h0;	// \\playground\\src\\PuaCpu.scala:6:7, :14:20
  assign io_data_sram_addr = 32'h0;	// \\playground\\src\\PuaCpu.scala:6:7, :14:20
  assign io_data_sram_wdata = 64'h0;	// \\playground\\src\\PuaCpu.scala:6:7, :14:20
  assign io_data_sram_wen = 8'h0;	// \\playground\\src\\PuaCpu.scala:6:7, :14:20
endmodule

